// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATvaR1fTsb0uVnSuuheVdBGD4lnngVkxA',
    appId: '1:461913651699:web:5ac47c8ae7743694653a86',
    messagingSenderId: '461913651699',
    projectId: 'codemate-6f2ce',
    authDomain: 'codemate-6f2ce.firebaseapp.com',
    storageBucket: 'codemate-6f2ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUnLV54dcaLmpU04cym8Eb7Mb1O5HI6ZQ',
    appId: '1:461913651699:android:b4e77b50952b1d34653a86',
    messagingSenderId: '461913651699',
    projectId: 'codemate-6f2ce',
    storageBucket: 'codemate-6f2ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCFW6dk6ACHnv87-7nKWr-u_Bpkbl_B6E',
    appId: '1:461913651699:ios:4f58bf7051e4ff6f653a86',
    messagingSenderId: '461913651699',
    projectId: 'codemate-6f2ce',
    storageBucket: 'codemate-6f2ce.firebasestorage.app',
    iosBundleId: 'com.example.codeMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCFW6dk6ACHnv87-7nKWr-u_Bpkbl_B6E',
    appId: '1:461913651699:ios:4f58bf7051e4ff6f653a86',
    messagingSenderId: '461913651699',
    projectId: 'codemate-6f2ce',
    storageBucket: 'codemate-6f2ce.firebasestorage.app',
    iosBundleId: 'com.example.codeMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATvaR1fTsb0uVnSuuheVdBGD4lnngVkxA',
    appId: '1:461913651699:web:6bf802f62fc65754653a86',
    messagingSenderId: '461913651699',
    projectId: 'codemate-6f2ce',
    authDomain: 'codemate-6f2ce.firebaseapp.com',
    storageBucket: 'codemate-6f2ce.firebasestorage.app',
  );
}
